Add .py support
saquibshaikh14/vscode-add-signature-extensoin pull request #1
Opened 2024-05-30 22:08 UTC by TRC-Loop

I just added .py support cuz I want python in the extension.

2024-06-02 03:47 UTC, saquibshaikh14 requested changes
Missing comment closing tag.

2024-06-02 11:55 UTC, TRC-Loop reviewed
Fixed.

2024-06-02 12:03 UTC, TRC-Loop reviewed
Fixed a Comment bug wirh Python.

2024-06-03 03:35 UTC, saquibshaikh14 approved these changes

2024-06-03 03:35 UTC, merged